#!/bin/bash
# ---------------------------------------------------
#  /usr/local/bin/device2mqtt
#
#  This script inspect devices on a LAN
#  and publish the arrival and departure 
#  thru a MQTT broker
#  Any device with a mDNS name will be detected
#  and reported on a MQTT topic
#  You just need to adapt local parameters
#  to your environment
#
#  MQTT will look like :
#    home/device/Pixel-Nicolas.lan ON
#    home/device/Pixel-Nicolas.lan OFF
#    home/device/Pixel-Nicolas.lan ON
#    home/device/Pixel-Nicolas.lan OFF
#
#  Revision history :
#   22/03/2026, v1.0 - Creation by N. Bernaerts
#
# ---------------------------------------------------

# global parameters
TIMEOUT=60
TMP_DATABASE="/tmp/device2mqtt.db"

# local parameters
NETMASK="192.168.1.0/24"
MQTT_SERVER="your.mqtt.server"
MQTT_PORT="1883"
MQTT_USER="your-user"
MQTT_PASSWORD="your-password"
MQTT_TOPIC="home/device"

# check tools availability
command -v nmap >/dev/null 2>&1 || { echo "[error] Please install nmap"; exit 1; }

# main infinite loop
while true
do
  # get dates
  TIMESTAMP=$(date "+%s")
  TIMEHHMM=$(date "+%H:%M")

  # create database
  [ ! -f "${TMP_DATABASE}" ] && touch "${TMP_DATABASE}"

  # look for new device or address change
  # -------------------------------------
  echo -ne "| \r" >&2
  ARR_DEVICE=( $(nmap -sPn "${NETMASK}" | grep "Nmap scan" | grep "(" | cut -d' ' -f5-6 | tr -d "()" | tr ' ' ';' | sed "s|\..*;|;|g" | sed "s|-[0-9]*;|;|g") )
  for DEVICE in "${ARR_DEVICE[@]}"
  do
    # if newly detected
    NAME=$(echo "${DEVICE}" | cut -d';' -f1)
    ADDRESS=$(echo "${DEVICE}" | cut -d';' -f2)

    # if device known, remove if IP has changed
    DEVICE_KNOWN=$(grep "^${NAME};" "${TMP_DATABASE}")
    if [ "${DEVICE_KNOWN}" != "" ]
    then
      DEVICE_ADDRESS=$(echo "${DEVICE_KNOWN}" | cut -d';' -f2)
      [ "${DEVICE_ADDRESS}" != "${ADDRESS}" ] && sed -i "/^${NAME};.*/d" "${TMP_DATABASE}"
    fi

    # if device unknown, check IP address and add it to database
    DEVICE_KNOWN=$(grep "^${NAME};" "${TMP_DATABASE}")
    if [ "${DEVICE_KNOWN}" = "" ]
    then
      IS_PRESENT=$(ping -w 1 -c 1 "${ADDRESS}" | grep "1 received")
      if [ "${IS_PRESENT}" != "" ]
      then
        echo "${TIMEHHMM} ${NAME} detected" >&2
        echo "${NAME};${ADDRESS};${TIMESTAMP}" >> "${TMP_DATABASE}"
        mosquitto_pub -h "${MQTT_SERVER}" -p ${MQTT_PORT} -u "${MQTT_USER}" -P "${MQTT_PASSWORD}" -t "${MQTT_TOPIC}/${NAME}" -m "ON"
      fi
    fi
  done

  # check devices
  # -------------
  echo -ne "/ \r" >&2
  ARR_DEVICE=( $(cat "${TMP_DATABASE}" | cut -d';' -f1,2) )
  for DEVICE in "${ARR_DEVICE[@]}"
  do
    # check device status
    NAME=$(echo "${DEVICE}" | cut -d';' -f1)
    ADDRESS=$(echo "${DEVICE}" | cut -d';' -f2)

    # if device is reachable, declare new timestamp
    IS_PRESENT=$(ping -w 1 -c 1 "${ADDRESS}" | grep "1 received")
    if [ "${IS_PRESENT}" != "" ]
    then
      sed -i "/^${NAME};.*/d" "${TMP_DATABASE}"
      echo "${NAME};${ADDRESS};${TIMESTAMP}" >> "${TMP_DATABASE}"
    fi
  done

  # detect devices which have left
  # ------------------------------
  echo -ne "- \r" >&2
  ARR_DEVICE=( $(cat "${TMP_DATABASE}" | cut -d';' -f1,3) )
  for DEVICE in "${ARR_DEVICE[@]}"
  do
    # check device status
    NAME=$(echo "${DEVICE}" | cut -d';' -f1)
    DETECTION=$(echo "${DEVICE}" | cut -d';' -f2)

    # if timeout is reached, remove device from database and publish exit
    DELAY=$((TIMESTAMP - DETECTION))
    if [ ${DELAY} -gt ${TIMEOUT} ]
    then
      echo "${TIMEHHMM} ${NAME} has left" >&2
      sed -i "/^${NAME};.*/d" "${TMP_DATABASE}"
      mosquitto_pub -h "${MQTT_SERVER}" -p ${MQTT_PORT} -u "${MQTT_USER}" -P "${MQTT_PASSWORD}" -t "${MQTT_TOPIC}/${NAME}" -m "OFF"
    fi
  done

  # wait for 5 seconds
  echo -ne "\\ \r" >&2
  sleep 5
done

