#!/bin/bash
# ------------------------------------------------------------------------
# Script to backup server databases and filesystems
#
#  Revision history :
#   08/10/2012, V1.0 - Creation by N. Bernaerts
#   22/01/2016, V1.1 - Add Telegram notification
#   15/10/2017, V1.3 - Minimize logs and backup calls
# ------------------------------------------------------------------------

# set PATH as it is not set for udev scripts
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# temporary backup files
NOTIF_BODY=$(mktemp -t backup-server-XXXXXXXX.txt)

# logger header
LOG_HEAD=$(date +"BCK%d%m")

# ---------------
#  Configuration
# ---------------

NOTIFY_EMAIL="no"
NOTIFY_TELEGRAM="yes"

# --------
#  Backup
# --------

#  Backup database
backup-database "/root/backup/database.data" "${LOG_HEAD}"

#  Backup files on local NAS
backup-rsync "/root/backup/rsync-NAS.data" "${LOG_HEAD}"

#  Backup files on distant NAS (PCA)
backup-rsync "/root/backup/rsync-PCA.data" "${LOG_HEAD}"

# --------------------
#  Email notification
# --------------------

if [ "${NOTIFY_EMAIL}" = "yes" ]
then
	# mail parameters
	MAIL_SUBJ="Server Backup"
	MAIL_DEST="your.address@your.mail.provider"

	#  Append Success or Error to email subject
	[ -s "${LOG_ERROR}" ] && MAIL_SUBJ="Error : $MAIL_SUBJ" || MAIL_SUBJ="Success : $MAIL_SUBJ"

	#  Add system log to email body
	echo "" > "${NOTIF_BODY}"
	echo "--- System log ---" >> "${NOTIF_BODY}"
	echo "" >> "${NOTIF_BODY}"
	cat /var/log/user.log | grep "$LOG_HEAD" >> "${NOTIF_BODY}"

	#  Send backup notification email
	send-email "$MAIL_DEST" "$MAIL_SUBJ" "${NOTIF_BODY}"
fi

# -----------------------
#  Telegram notification
# -----------------------

if [ "${NOTIFY_EMAIL}" = "yes" ]
then
	# telegram parameters
	NOTIF_SUBJ="Server Backup"

	#  Set backup icon
	[ -s "${LOG_ERROR}" ] && NOTIF_ICON="error" || NOTIF_ICON="success"

	#  Add system log to telegram notification body body
	#       Jan 17 06:25:06 your-server root: BCK1701 - Success - NAS : /mnt/.../database
	#  becomes
	#       Success 06:25 NAS : /mnt/.../database
	cat /var/log/user.log | grep "${LOG_HEAD}" | sed "s/^.* [0-9]* \([0-9:]*\):[0-9]* .* - \(.*\) - \(.*\)$/\2 \1 \3/" > "${NOTIF_BODY}"
	sed -i "s/Success/"$'\U0001F539'"/g" "${NOTIF_BODY}"
	sed -i "s/Error/"$'\U0001F53B'"/g" "${NOTIF_BODY}"

	#  Send backup notification thru Telegram
	telegram-notify --${NOTIF_ICON} --title "${NOTIF_SUBJ}" --text "${NOTIF_BODY}"
fi

# remove temporary files
rm -f "${NOTIF_BODY}"
