#!/bin/bash
# ------------------------------------------------------------------------
# Script to backup server databases and filesystems
#
#  Revision history :
#   08/10/2012, V1.0 - Creation by N. Bernaerts
#   22/01/2016, V1.1 - Add Telegram notification
# ------------------------------------------------------------------------

# set PATH as it is not set for udev scripts
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# backup log
LOG_ERROR="/tmp/daily-error.log"
LOG_BACKUP="/tmp/daily-backup.log"

# logger header
LOG_HEAD=$(date +"BCK%d%m")

# reset the backup log
[ -f $LOG_ERROR  ] && rm $LOG_ERROR
[ -f $LOG_BACKUP ] && rm $LOG_BACKUP

# ------------------------------------------
#  Backup
# ------------------------------------------

#  Backup database
backup-database "${LOG_HEAD}" "${LOG_BACKUP}" "${LOG_ERROR}"

#  Backup files on local NAS
backup-rsync "NAS" "${LOG_HEAD}" "${LOG_BACKUP}" "${LOG_ERROR}"

#  Backup files on distant NAS (PCA)
backup-rsync "PCA" "${LOG_HEAD}" "${LOG_BACKUP}" "${LOG_ERROR}"

# ------------------------------------------
#  Email notification
# ------------------------------------------

# mail parameters
MAIL_SUBJ="Daily Backup"
MAIL_DEST="your.address@your.mail.provider"
MAIL_BODY="/tmp/daily-email.log"

#  Append Success or Error to email subject
[ -s "${LOG_ERROR}" ] && MAIL_SUBJ="Error : $MAIL_SUBJ" || MAIL_SUBJ="Success : $MAIL_SUBJ"

#  Add system log to email body
echo "" > $MAIL_BODY
echo "------------ System log -------------" >> $MAIL_BODY
echo "" >> $MAIL_BODY
cat /var/log/user.log | grep "$LOG_HEAD" >> $MAIL_BODY

#  Add backup log to email body
echo "" >> $MAIL_BODY
echo "------------ Operation log -------------" >> $MAIL_BODY
echo "" >> $MAIL_BODY
cat $LOG_BACKUP >> $MAIL_BODY

#  Send backup notification email
#send-email "$MAIL_DEST" "$MAIL_SUBJ" "$MAIL_BODY"

# ------------------------------------------
#  Telegram notification
# ------------------------------------------

# telegram parameters
NOTIF_SUBJ="Server Backup"
NOTIF_BODY="/tmp/daily-notification.log"

#  Set backup icon
[ -s "${LOG_ERROR}" ] && NOTIF_ICON="error" || NOTIF_ICON="success"

#  Add system log to telegram notification body body
#    Jan 17 06:25:06 your-server root: BCK1701 - Success - NAS : /mnt/.../database
#   becomes
#    Success 06:25 NAS : /mnt/.../database
cat /var/log/user.log | grep "$LOG_HEAD" | sed "s/^.* [0-9]* \([0-9:]*\):[0-9]* .* - \(.*\) - \(.*\)$/\2 \1 \3/" > ${NOTIF_BODY}
sed -i "s/Success/"$'\U00002714'"/g" ${NOTIF_BODY}
sed -i "s/Error/"$'\U00002716'"/g" ${NOTIF_BODY}

#  Send backup notification thru Telegram
telegram-notify --${NOTIF_ICON} --title "${NOTIF_SUBJ}" --file ${NOTIF_BODY}

# end
exit
