#!/bin/bash
# --------------------------------------------------------
# Script to backup databases on a server
#
# Parameters :
#  $1 - database backup description file
#
#  Revision history :
#   08/06/2013, V1.0 - Creation by N. Bernaerts
#   08/11/2013, V1.2 - Change parameters
#   15/10/2017, V1.3 - Merge configuration in single file
# --------------------------------------------------------

# set PATH as it is not set for udev scripts
PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# parameters
DATABASE_DATA="$1"

# log header
LOG_HEADER=$(date +"BCK%d%m")

# temporary files
DATABASE_LIST=$(mktemp -t backup-rsync-XXXXXXXX.lst)

# display
echo "${LOG_HEADER} Database : Start"

# set backup parameters
DATABASE_PASSWD="$(cat ${DATABASE_DATA} | grep "password="   | cut -d'=' -f2-)"
DATABASE_PATH="$(cat ${DATABASE_DATA} | grep "backupdir="   | cut -d'=' -f2-)"

# generate backup directories list
grep "^base=" "${DATABASE_DATA}" > "${DATABASE_LIST}"

# if needed, create backup directory
mkdir -p "${DATABASE_PATH}"

# loop thru the backup list
while read LINE
do
	# keep line content
	CONTENT=$(echo "${LINE}" | cut -d'=' -f2-)

	# extract database data
	DATABASE_LABEL=$(echo "${CONTENT}" | cut -d';' -f1)
	DATABASE_NAME=$(echo "${LINE}" | cut -d';' -f2)

	# display and log the backup
	echo "${LOG_HEADER} Database : ${DATABASE_LABEL}"
	logger "$1 - Success - Database ${DATABASE_LABEL}"

	# database dump
	mysqldump -u root "-p${DATABASE_PASSWD}" "${DATABASE_NAME}" > "${DATABASE_PATH}/${DATABASE_NAME}.sql"
done < "${DATABASE_LIST}"

# display
echo "${LOG_HEADER} Database : End"

# remove temporary files
rm -f "${DATABASE_LIST}"
