#!/bin/bash
# --------------------------------------------------------
# Script to backup server databases
#
# This script uses the following tools :
#  * rsync
#
# Parameters :
#  $1 - rsync backup description file
#  $2 - log header
#
#  Revision history :
#   08/06/2013, V1.0 - Creation by N. Bernaerts
#   04/11/2013, V1.1 - Handle error cases & log
#   08/11/2013, V1.2 - Change parameters
#   15/10/2017, V1.3 - Merge configuration in single file
# --------------------------------------------------------

# set PATH (in case)
PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# retreive parameters
BACKUP_DATA="$1"
LOG_HEADER="$2"

# temporary files
TMP_PASSWD=$(mktemp -t backup-rsync-XXXXXXXX.pwd)
LOG_CURRENT=$(mktemp -t backup-rsync-XXXXXXXX.log)
BACKUP_LIST=$(mktemp -t backup-rsync-XXXXXXXX.lst)

# set backup parameters
BACKUP_NAME="$(cat ${BACKUP_DATA} | grep "name="   | cut -d'=' -f2-)"
BACKUP_SERVER="$(cat ${BACKUP_DATA} | grep "server="   | cut -d'=' -f2-)"
BACKUP_PORT="$(cat ${BACKUP_DATA}   | grep "port="     | cut -d'=' -f2-)"
BACKUP_MODULE="$(cat ${BACKUP_DATA} | grep "module="   | cut -d'=' -f2-)"
BACKUP_USER="$(cat ${BACKUP_DATA}   | grep "user="     | cut -d'=' -f2-)"
BACKUP_PASSWD="$(cat ${BACKUP_DATA} | grep "password=" | cut -d'=' -f2-)"
BACKUP_OPTION="$(cat ${BACKUP_DATA} | grep "option="   | cut -d'=' -f2-)"

# display
echo "${LOG_HEADER} RSync : ${BACKUP_NAME} - Start"

# generate backup directories list
grep "^dir=" "${BACKUP_DATA}" > "${BACKUP_LIST}"

# create password file
echo "${BACKUP_PASSWD}" > "${TMP_PASSWD}"
chmod 0700 "${TMP_PASSWD}"

# loop thru the backup list
while read LINE
do
	# keep line content
	CONTENT=$(echo "${LINE}" | cut -d'=' -f2-)

	# extract directory data
	DIRECTORY_LABEL=$(echo "${CONTENT}" | cut -d';' -f1)
	DIRECTORY_PATH=$(echo "${CONTENT}" | cut -d';' -f2)
	DIRECTORY_EXCLUDE=$(echo "${CONTENT}" | cut -d';' -f3)

	# if backup dir exists, start the backup
	if [ -d "$DIRECTORY_PATH" ]
	then
		# set options
		ARR_OPTION=( $(echo ${BACKUP_OPTION}) )
		[ "$DIRECTORY_EXCLUDE" != "" ] && ARR_OPTION=( "${ARR_OPTION[@]}" "--exclude=${DIRECTORY_EXCLUDE}" )

		# beginning of backup
		echo "${LOG_HEADER} RSync : ${BACKUP_NAME} - ${DIRECTORY_PATH} ("${ARR_OPTION[@]}")"

		# backup the directory structure
		rsync "${ARR_OPTION[@]}" "--password-file=${TMP_PASSWD}" "${DIRECTORY_PATH}" "rsync://${BACKUP_USER}@${BACKUP_SERVER}:${BACKUP_PORT}/${BACKUP_MODULE}" > "${LOG_CURRENT}"

		# log success or error
		LOG_LINE=$(wc -l "${LOG_CURRENT}" | cut -d' ' -f1)
		[ "$LOG_LINE" -gt 0 ] && RESULT="Success" || RESULT="Error"
		logger "${LOG_HEADER} - ${RESULT} - Rsync ${BACKUP_NAME} : ${DIRECTORY_PATH}"


	# else, directory not present
	else
		logger "${LOG_HEADER} - Error - Rsync ${BACKUP_NAME} : Absent directory ${DIRECTORY_PATH}"
	fi
done < "${BACKUP_LIST}"

# display
echo "${LOG_HEADER} RSync : ${BACKUP_NAME} - End"

# remove temporary files
rm -f "${BACKUP_LIST}" "${TMP_PASSWD}" "${LOG_CURRENT}"
