#!/bin/bash
# ------------------------------------------------------------------------
# Script to backup server databases and filesystems
#
#  Revision history :
#   08/10/2012, V1.0 - Creation by N. Bernaerts
#   22/01/2016, V1.1 - Add Telegram notification
#   15/10/2017, V1.3 - Minimize logs and backup calls
#   05/10/2019, V1.4 - Change log management
# ------------------------------------------------------------------------

# set PATH as it is not set for udev scripts
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# temporary files
TMP_DIR=$(mktemp --tmpdir --directory backup-rsync-XXXXXX)
TMP_LOG="${TMP_DIR}/backup.log"
TMP_MSG="${TMP_DIR}/message.txt"

# ---------------
#  Configuration
# ---------------

# notification media
NOTIFY_EMAIL="no"
NOTIFY_TELEGRAM="yes"

# notification title
NOTIFY_TITLE="Server backup"

# --------
#  Backup
# --------

#  Backup database
backup-database "/root/backup/database.data" "${TMP_LOG}"

#  Backup files on local NAS
backup-rsync "/root/backup/rsync-NAS.data" "${TMP_LOG}"

#  Backup files on distant NAS (PCA)
backup-rsync "/root/backup/rsync-PCA.data" "${TMP_LOG}"

# check if backup has got errors
HAS_ERROR=$(cat "${TMP_LOG}" | grep "error")

# --------------------
#  Email notification
# --------------------

if [ "${NOTIFY_EMAIL}" = "yes" ]
then
	# mail parameters
	MAIL_DEST="your.address@your.mail.provider"

	#  Append Success or Error to email subject
	[ "${HAS_ERROR}" != "" ] && MAIL_TITLE="Error : ${NOTIF_TITLE}" || MAIL_TITLE="Success : ${NOTIF_TITLE}"

	#  Generate message from logs
	cat "${TMP_LOG}" > "${TMP_MSG}"

	#  Send backup notification email
	send-email "${MAIL_DEST}" "${MAIL_TITLE}" "${TMP_MSG}"
fi

# -----------------------
#  Telegram notification
# -----------------------

if [ "${NOTIFY_TELEGRAM}" = "yes" ]
then
	#  Set backup icon
	[ "${HAS_ERROR}" != "" ] && NOTIFY_ICON="error" || NOTIFY_ICON="success"

	#  Add system log to telegram notification body body
	#       Jan 17 06:25:06 your-server root: BCK1701 - Success - NAS : /mnt/.../database
	#  becomes
	#       Success 06:25 NAS : /mnt/.../database
	cat "${TMP_LOG}" | sed -e "s/success/"$'\U0001F539'"/g" -e "s/error/"$'\U0001F53B'"/g" > "${TMP_MSG}"

	#  Send backup notification thru Telegram
	telegram-notify --${NOTIFY_ICON} --title "${NOTIFY_TITLE}" --text "${TMP_MSG}"
fi

# remove temporary files
rm -R "${TMP_DIR}"

